import { readFile } from 'fs/promises';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import { getOpenAI } from '../../config/openai.js';
import { getSupabaseAdmin } from '../../config/supabase.js';

const __dirname = dirname(fileURLToPath(import.meta.url));

/**
 * Generate (or return cached) a search profile for an ITP.
 *
 * Returns: {
 *   search_queries: string[],
 *   directory_whitelist: string[],
 *   negative_keywords: string[],
 *   buyer_descriptions: string[],
 *   company_name_keywords: string[],
 *   min_company_age_years: number,
 *   customer_sic_codes?: string[],  // preserved from previous profile if present
 * }
 *
 * @param {object} params
 * @param {object} params.itp              - Full ITP record from DB
 * @param {object} params.account          - Account record from DB
 * @param {string[]} [params.prior_rejection_reasons] - Rejection patterns from previous cycles
 * @param {boolean} [params.force]         - Force regeneration even if cached
 */
export async function generateQueryProfile({ itp, account, prior_rejection_reasons = [], force = false }) {
  // Return cached profile if valid and not forced.
  // A profile is considered valid if it has the new fields (directory_whitelist + negative_keywords).
  if (!force && itp.search_profile && isProfileValid(itp.search_profile)) {
    console.log(`[query_generator] Using cached search profile for ITP ${itp.id}`);
    return itp.search_profile;
  }

  console.log(`[query_generator] Generating search profile for ITP ${itp.id}${force ? ' (forced)' : ''}...`);

  const prompt = await readFile(join(__dirname, 'prompts/prompt_query_generate.md'), 'utf-8');

  const context = {
    account: {
      name: account.organisation_name ?? '',
      website: account.organisation_website ?? '',
      description: account.description ?? '',
      problem_solved: account.problem_solved ?? '',
    },
    itp: {
      name: itp.name ?? '',
      summary: itp.itp_summary ?? '',
      demographics: itp.itp_demographic ?? '',
      pain_points: itp.itp_pain_points ?? '',
      buying_trigger: itp.itp_buying_trigger ?? '',
      location: itp.location ?? '',
    },
    ...(prior_rejection_reasons.length > 0
      ? { prior_rejection_reasons }
      : {}),
  };

  const response = await getOpenAI().chat.completions.create({
    model: 'gpt-5',
    max_completion_tokens: 2048,
    messages: [
      { role: 'user', content: `${prompt}\n\n${JSON.stringify(context, null, 2)}` },
    ],
  });

  const raw = response.choices[0].message.content.trim()
    .replace(/^```(?:json)?\s*/i, '').replace(/```\s*$/, '');

  let profile;
  try {
    profile = JSON.parse(raw);
  } catch {
    const preview = raw.slice(0, 300);
    console.error('[query_generator] Failed to parse LLM response:', preview);
    throw new Error('query_generator: LLM returned unparseable response');
  }

  // Preserve customer_sic_codes from previous profile if present — these come from
  // the analyse_customers skill and are not regenerated by the query generator.
  if (itp.search_profile?.customer_sic_codes?.length) {
    profile.customer_sic_codes = itp.search_profile.customer_sic_codes;
  }

  // Persist to DB
  await getSupabaseAdmin()
    .from('itp')
    .update({ search_profile: profile })
    .eq('id', itp.id);

  console.log(
    `[query_generator] Profile generated: ${profile.search_queries?.length ?? 0} queries, ` +
    `${profile.directory_whitelist?.length ?? 0} directory entries, ` +
    `${profile.negative_keywords?.length ?? 0} negative keywords`
  );

  return profile;
}

/**
 * Clear the cached search profile for an ITP.
 * Must be called by itp_refiner_v2 whenever a diff is applied,
 * so the next run generates a fresh profile incorporating the refined ITP.
 */
export async function clearQueryProfileCache(itpId) {
  await getSupabaseAdmin()
    .from('itp')
    .update({ search_profile: null })
    .eq('id', itpId);
  console.log(`[query_generator] Cache cleared for ITP ${itpId} — will regenerate on next run`);
}

function isProfileValid(profile) {
  return (
    Array.isArray(profile.search_queries) &&
    Array.isArray(profile.directory_whitelist) &&
    Array.isArray(profile.negative_keywords) &&
    Array.isArray(profile.buyer_descriptions)
  );
}
